spring:
  config:
    # import: "optional:configserver:http://192.168.100.221:30614/"
    import: "optional:configserver:http://localhost:8762/"
    fail-fast: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/