---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team6-eureka-client-account
  namespace: group1-team6
spec:
  replicas: 3
  selector:
    matchLabels:
      app: team6-eureka-client-account
  template:
    metadata:
      labels:
        app: team6-eureka-client-account
    spec:
      containers:
      - name: team6-eureka-client-account
        image: k8s-vga-worker1:5000/group1-team6-eureka-client-account:v0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9010
---
apiVersion: v1
kind: Service
metadata:
  name: team6-eureka-client-account
  namespace: group1-team6
spec:
  selector:
    app: team6-eureka-client-account
  ports:
    - protocol: TCP
      port: 9010
      targetPort: 9010
      nodePort: 30614
  type: NodePort
